# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-25 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuguide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftbeer',
            name='Picture',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
